package com.MinhaoZhang.Chemistry;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Blocks;
import net.minecraft.block.Material;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


public class Chemistry implements ModInitializer {
    public static final Logger LOGGER = LogManager.getLogger("chem");
    public static final String MOD_ID = "chem";
    public static final ItemGroup CHEM_ELEMENT_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "element"), () -> new ItemStack(Blocks.CAULDRON));
    public static final ItemGroup CHEM_ITEM_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "general"), () -> new ItemStack(Blocks.BREWING_STAND));
    public static final ChemBlock HYDROGEN = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock HELIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock LITHIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BERYLLIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BORON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CARBON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NITROGEN = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock OXYGEN = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock FLUORINE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NEON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SODIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MAGNESIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ALUMINIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SILICON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PHOSPHORUS = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SULFUR = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CHLORINE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ARGON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock POTASSIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CALCIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SCANDIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TITANIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock VANADIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CHROMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MANGANESE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock IRON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock COBALT = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NICKEL = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock COPPER = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ZINC = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock GALLIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock GERMANIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ARSENIC = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SELENIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BROMINE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock KRYPTON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RUBIDIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock STRONTIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock YTTRIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ZIRCONIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NIOBIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MOLYBDENUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TECHNETIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RUTHENIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RHODIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PALLADIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SILVER = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CADMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock INDIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TIN = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ANTIMONY = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TELLURIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock IODINE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock XENON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CESIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BARIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock LANTHANUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CERIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PRASEODYMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NEODYMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PROMETHIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SAMARIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock EUROPIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock GADOLINIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TERBIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock DYSPROSIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock HOLMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ERBIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock THULIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock YTTERBIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock LUTETIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock HAFNIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TANTALUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TUNGSTEN = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RHENIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock OSMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock IRIDIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PLATINUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock GOLD = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MERCURY = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock THALLIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock LEAD = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BISMUTH = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock POLONIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ASTATINE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RADON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock FRANCIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RADIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ACTINIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock THORIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PROTACTINIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock URANIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NEPTUNIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock PLUTONIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock AMERICIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CURIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BERKELIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock CALIFORNIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock EINSTEINIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock FERMIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MENDELEVIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NOBELIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock LAWRENCIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock RUTHERFORDIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock DUBNIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock SEABORGIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock BOHRIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock HASSIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MEITNERIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock DARMSTADTIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock ROENTGENIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock COPERNICIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock NIHONIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock FLEROVIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock MOSCOVIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock LIVERMORIUM = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock TENNESSINE = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemBlock OGANESSON = new ChemBlock(FabricBlockSettings.of(Material.METAL).strength(1.5f, 3600000f).requiresTool().luminance(15));
    public static final ChemItem HYDROGEN_GAS = new ChemItem(new FabricItemSettings().group(CHEM_ITEM_GROUP).maxCount(16).food(new FoodComponent.Builder().hunger(0).saturationModifier(0).alwaysEdible().snack().statusEffect(new StatusEffectInstance(StatusEffects.LEVITATION, 60*20), 1).build()));
    public static final ChemItem HELIUM_GAS = new ChemItem(new FabricItemSettings().group(CHEM_ITEM_GROUP).maxCount(16).food(new FoodComponent.Builder().hunger(0).saturationModifier(0).alwaysEdible().snack().statusEffect(new StatusEffectInstance(StatusEffects.LEVITATION, 60*20), 1).build()));

    @Override
    public void onInitialize() {
        LOGGER.info("Hello Fabric world!");
        registerAll();
    }

    private void registerAll() {
        registerItem();
        registerBlock();
        registerBlockItem();
    }

    private void registerItem() {
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hydrogen_gas"), HYDROGEN_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "helium_gas"), HELIUM_GAS);
    }

    private void registerBlock() {
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "hydrogen"), HYDROGEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "helium"), HELIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lithium"), LITHIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "beryllium"), BERYLLIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "boron"), BORON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "carbon"), CARBON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nitrogen"), NITROGEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "oxygen"), OXYGEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "fluorine"), FLUORINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "neon"), NEON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "sodium"), SODIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "magnesium"), MAGNESIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "aluminium"), ALUMINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "silicon"), SILICON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "phosphorus"), PHOSPHORUS);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "sulfur"), SULFUR);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "chlorine"), CHLORINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "argon"), ARGON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "potassium"), POTASSIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "calcium"), CALCIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "scandium"), SCANDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "titanium"), TITANIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "vanadium"), VANADIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "chromium"), CHROMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "manganese"), MANGANESE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "iron"), IRON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cobalt"), COBALT);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nickel"), NICKEL);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "copper"), COPPER);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "zinc"), ZINC);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "gallium"), GALLIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "germanium"), GERMANIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "arsenic"), ARSENIC);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "selenium"), SELENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "bromine"), BROMINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "krypton"), KRYPTON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rubidium"), RUBIDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "strontium"), STRONTIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "yttrium"), YTTRIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "zirconium"), ZIRCONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "niobium"), NIOBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "molybdenum"), MOLYBDENUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "technetium"), TECHNETIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "ruthenium"), RUTHENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rhodium"), RHODIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "palladium"), PALLADIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "silver"), SILVER);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cadmium"), CADMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "indium"), INDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tin"), TIN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "antimony"), ANTIMONY);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tellurium"), TELLURIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "iodine"), IODINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "xenon"), XENON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cesium"), CESIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "barium"), BARIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lanthanum"), LANTHANUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cerium"), CERIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "praseodymium"), PRASEODYMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "neodymium"), NEODYMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "promethium"), PROMETHIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "samarium"), SAMARIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "europium"), EUROPIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "gadolinium"), GADOLINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "terbium"), TERBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "dysprosium"), DYSPROSIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "holmium"), HOLMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "erbium"), ERBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "thulium"), THULIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "ytterbium"), YTTERBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lutetium"), LUTETIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "hafnium"), HAFNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tantalum"), TANTALUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tungsten"), TUNGSTEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rhenium"), RHENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "osmium"), OSMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "iridium"), IRIDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "platinum"), PLATINUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "gold"), GOLD);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "mercury"), MERCURY);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "thallium"), THALLIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lead"), LEAD);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "bismuth"), BISMUTH);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "polonium"), POLONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "astatine"), ASTATINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "radon"), RADON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "francium"), FRANCIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "radium"), RADIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "actinium"), ACTINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "thorium"), THORIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "protactinium"), PROTACTINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "uranium"), URANIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "neptunium"), NEPTUNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "plutonium"), PLUTONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "americium"), AMERICIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "curium"), CURIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "berkelium"), BERKELIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "californium"), CALIFORNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "einsteinium"), EINSTEINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "fermium"), FERMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "mendelevium"), MENDELEVIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nobelium"), NOBELIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lawrencium"), LAWRENCIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rutherfordium"), RUTHERFORDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "dubnium"), DUBNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "seaborgium"), SEABORGIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "bohrium"), BOHRIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "hassium"), HASSIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "meitnerium"), MEITNERIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "darmstadtium"), DARMSTADTIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "roentgenium"), ROENTGENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "copernicium"), COPERNICIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nihonium"), NIHONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "flerovium"), FLEROVIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "moscovium"), MOSCOVIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "livermorium"), LIVERMORIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tennessine"), TENNESSINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "oganesson"), OGANESSON);
    }

    private void registerBlockItem() {
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hydrogen"), new BlockItem(HYDROGEN, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "helium"), new BlockItem(HELIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lithium"), new BlockItem(LITHIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "beryllium"), new BlockItem(BERYLLIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "boron"), new BlockItem(BORON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "carbon"), new BlockItem(CARBON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nitrogen"), new BlockItem(NITROGEN, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "oxygen"), new BlockItem(OXYGEN, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "fluorine"), new BlockItem(FLUORINE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neon"), new BlockItem(NEON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "sodium"), new BlockItem(SODIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "magnesium"), new BlockItem(MAGNESIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "aluminium"), new BlockItem(ALUMINIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "silicon"), new BlockItem(SILICON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "phosphorus"), new BlockItem(PHOSPHORUS, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "sulfur"), new BlockItem(SULFUR, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "chlorine"), new BlockItem(CHLORINE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "argon"), new BlockItem(ARGON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "potassium"), new BlockItem(POTASSIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "calcium"), new BlockItem(CALCIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "scandium"), new BlockItem(SCANDIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "titanium"), new BlockItem(TITANIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "vanadium"), new BlockItem(VANADIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "chromium"), new BlockItem(CHROMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "manganese"), new BlockItem(MANGANESE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "iron"), new BlockItem(IRON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cobalt"), new BlockItem(COBALT, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nickel"), new BlockItem(NICKEL, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "copper"), new BlockItem(COPPER, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "zinc"), new BlockItem(ZINC, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "gallium"), new BlockItem(GALLIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "germanium"), new BlockItem(GERMANIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "arsenic"), new BlockItem(ARSENIC, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "selenium"), new BlockItem(SELENIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bromine"), new BlockItem(BROMINE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "krypton"), new BlockItem(KRYPTON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rubidium"), new BlockItem(RUBIDIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "strontium"), new BlockItem(STRONTIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "yttrium"), new BlockItem(YTTRIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "zirconium"), new BlockItem(ZIRCONIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "niobium"), new BlockItem(NIOBIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "molybdenum"), new BlockItem(MOLYBDENUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "technetium"), new BlockItem(TECHNETIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "ruthenium"), new BlockItem(RUTHENIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rhodium"), new BlockItem(RHODIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "palladium"), new BlockItem(PALLADIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "silver"), new BlockItem(SILVER, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cadmium"), new BlockItem(CADMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "indium"), new BlockItem(INDIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tin"), new BlockItem(TIN, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "antimony"), new BlockItem(ANTIMONY, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tellurium"), new BlockItem(TELLURIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "iodine"), new BlockItem(IODINE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "xenon"), new BlockItem(XENON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cesium"), new BlockItem(CESIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "barium"), new BlockItem(BARIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lathanum"), new BlockItem(LANTHANUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cerium"), new BlockItem(CERIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "praseodymium"), new BlockItem(PRASEODYMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neodymium"), new BlockItem(NEODYMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "promethium"), new BlockItem(PROMETHIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "samarium"), new BlockItem(SAMARIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "europium"), new BlockItem(EUROPIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "gadolinium"), new BlockItem(GADOLINIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "terbium"), new BlockItem(TERBIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "dysprosium"), new BlockItem(DYSPROSIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "holmium"), new BlockItem(HOLMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "erbium"), new BlockItem(ERBIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "thulium"), new BlockItem(THULIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "ytterbium"), new BlockItem(YTTERBIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lutetium"), new BlockItem(LUTETIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hafnium"), new BlockItem(HAFNIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tantalum"), new BlockItem(TANTALUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tungsten"), new BlockItem(TUNGSTEN, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rhenium"), new BlockItem(RHENIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "osmium"), new BlockItem(OSMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "iridium"), new BlockItem(IRIDIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "platium"), new BlockItem(PLATINUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "gold"), new BlockItem(GOLD, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "mercury"), new BlockItem(MERCURY, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "thallium"), new BlockItem(THALLIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lead"), new BlockItem(LEAD, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bismuth"), new BlockItem(BISMUTH, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "polonium"), new BlockItem(POLONIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "astatine"), new BlockItem(ASTATINE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "radon"), new BlockItem(RADON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "francium"), new BlockItem(FRANCIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "radium"), new BlockItem(RADIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "actinium"), new BlockItem(ACTINIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "thorium"), new BlockItem(THORIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "protactinium"), new BlockItem(PROTACTINIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "uranium"), new BlockItem(URANIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neptunium"), new BlockItem(NEPTUNIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "plutonium"), new BlockItem(PLUTONIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "americium"), new BlockItem(AMERICIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "curium"), new BlockItem(CURIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "berkelium"), new BlockItem(BERKELIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "californium"), new BlockItem(CALIFORNIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "einsteinium"), new BlockItem(EINSTEINIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "fermium"), new BlockItem(FERMIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "mendelevium"), new BlockItem(MENDELEVIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nobelium"), new BlockItem(NOBELIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lawrencium"), new BlockItem(LAWRENCIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rutherfordium"), new BlockItem(RUTHERFORDIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "dubnium"), new BlockItem(DUBNIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "seaborgium"), new BlockItem(SEABORGIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bohrium"), new BlockItem(BOHRIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hassium"), new BlockItem(HASSIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "meitnerium"), new BlockItem(MEITNERIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "darmstadtium"), new BlockItem(DARMSTADTIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "roentgenium"), new BlockItem(ROENTGENIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "copernicium"), new BlockItem(COPERNICIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nihonium"), new BlockItem(NIHONIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "flerovium"), new BlockItem(FLEROVIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "moscovium"), new BlockItem(MOSCOVIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "livermorium"), new BlockItem(LIVERMORIUM, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tennessine"), new BlockItem(TENNESSINE, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "oganesson"), new BlockItem(OGANESSON, new FabricItemSettings().group(CHEM_ELEMENT_GROUP)));
    }
}
