package com.MinhaoZhang.Chemistry;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.block.Blocks;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;
import net.minecraft.util.registry.Registry;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


public class Chemistry implements ModInitializer {
    public static final Logger LOGGER = LogManager.getLogger("chem");
    public static final String MOD_ID = "chem";
    public static final ItemGroup CHEM_ELEMENT_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "element"), () -> new ItemStack(Blocks.CAULDRON));
    public static final ItemGroup CHEM_GAS_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "gas"), () -> new ItemStack(Items.GLASS_BOTTLE));
    public static final ItemGroup CHEM_LIQUID_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "liquid"), () -> new ItemStack(Items.POTION));
    public static final ItemGroup CHEM_METAL_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "metal"), () -> new ItemStack(Items.IRON_BLOCK));
    public static final ItemGroup CHEM_ITEM_GROUP = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "general"), () -> new ItemStack(Blocks.BREWING_STAND));

    public static final ChemElement HYDROGEN = new ChemElement(1);
    public static final ChemElement HELIUM = new ChemElement(2);
    public static final ChemElement LITHIUM = new ChemElement(3);
    public static final ChemElement BERYLLIUM = new ChemElement(4);
    public static final ChemElement BORON = new ChemElement(5);
    public static final ChemElement CARBON = new ChemElement(6);
    public static final ChemElement NITROGEN = new ChemElement(7);
    public static final ChemElement OXYGEN = new ChemElement(8);
    public static final ChemElement FLUORINE = new ChemElement(9);
    public static final ChemElement NEON = new ChemElement(10);
    public static final ChemElement SODIUM = new ChemElement(11);
    public static final ChemElement MAGNESIUM = new ChemElement(12);
    public static final ChemElement ALUMINIUM = new ChemElement(13);
    public static final ChemElement SILICON = new ChemElement(14);
    public static final ChemElement PHOSPHORUS = new ChemElement(15);
    public static final ChemElement SULFUR = new ChemElement(16);
    public static final ChemElement CHLORINE = new ChemElement(17);
    public static final ChemElement ARGON = new ChemElement(18);
    public static final ChemElement POTASSIUM = new ChemElement(19);
    public static final ChemElement CALCIUM = new ChemElement(20);
    public static final ChemElement SCANDIUM = new ChemElement(21);
    public static final ChemElement TITANIUM = new ChemElement(22);
    public static final ChemElement VANADIUM = new ChemElement(23);
    public static final ChemElement CHROMIUM = new ChemElement(24);
    public static final ChemElement MANGANESE = new ChemElement(25);
    public static final ChemElement IRON = new ChemElement(26);
    public static final ChemElement COBALT = new ChemElement(27);
    public static final ChemElement NICKEL = new ChemElement(28);
    public static final ChemElement COPPER = new ChemElement(29);
    public static final ChemElement ZINC = new ChemElement(30);
    public static final ChemElement GALLIUM = new ChemElement(31);
    public static final ChemElement GERMANIUM = new ChemElement(32);
    public static final ChemElement ARSENIC = new ChemElement(33);
    public static final ChemElement SELENIUM = new ChemElement(34);
    public static final ChemElement BROMINE = new ChemElement(35);
    public static final ChemElement KRYPTON = new ChemElement(36);
    public static final ChemElement RUBIDIUM = new ChemElement(37);
    public static final ChemElement STRONTIUM = new ChemElement(38);
    public static final ChemElement YTTRIUM = new ChemElement(39);
    public static final ChemElement ZIRCONIUM = new ChemElement(40);
    public static final ChemElement NIOBIUM = new ChemElement(41);
    public static final ChemElement MOLYBDENUM = new ChemElement(42);
    public static final ChemElement TECHNETIUM = new ChemElement(43);
    public static final ChemElement RUTHENIUM = new ChemElement(44);
    public static final ChemElement RHODIUM = new ChemElement(45);
    public static final ChemElement PALLADIUM = new ChemElement(46);
    public static final ChemElement SILVER = new ChemElement(47);
    public static final ChemElement CADMIUM = new ChemElement(48);
    public static final ChemElement INDIUM = new ChemElement(49);
    public static final ChemElement TIN = new ChemElement(50);
    public static final ChemElement ANTIMONY = new ChemElement(51);
    public static final ChemElement TELLURIUM = new ChemElement(52);
    public static final ChemElement IODINE = new ChemElement(53);
    public static final ChemElement XENON = new ChemElement(54);
    public static final ChemElement CESIUM = new ChemElement(55);
    public static final ChemElement BARIUM = new ChemElement(56);
    public static final ChemElement LANTHANUM = new ChemElement(57);
    public static final ChemElement CERIUM = new ChemElement(58);
    public static final ChemElement PRASEODYMIUM = new ChemElement(59);
    public static final ChemElement NEODYMIUM = new ChemElement(60);
    public static final ChemElement PROMETHIUM = new ChemElement(61);
    public static final ChemElement SAMARIUM = new ChemElement(62);
    public static final ChemElement EUROPIUM = new ChemElement(63);
    public static final ChemElement GADOLINIUM = new ChemElement(64);
    public static final ChemElement TERBIUM = new ChemElement(65);
    public static final ChemElement DYSPROSIUM = new ChemElement(66);
    public static final ChemElement HOLMIUM = new ChemElement(67);
    public static final ChemElement ERBIUM = new ChemElement(68);
    public static final ChemElement THULIUM = new ChemElement(69);
    public static final ChemElement YTTERBIUM = new ChemElement(70);
    public static final ChemElement LUTETIUM = new ChemElement(71);
    public static final ChemElement HAFNIUM = new ChemElement(72);
    public static final ChemElement TANTALUM = new ChemElement(73);
    public static final ChemElement TUNGSTEN = new ChemElement(74);
    public static final ChemElement RHENIUM = new ChemElement(75);
    public static final ChemElement OSMIUM = new ChemElement(76);
    public static final ChemElement IRIDIUM = new ChemElement(77);
    public static final ChemElement PLATINUM = new ChemElement(78);
    public static final ChemElement GOLD = new ChemElement(79);
    public static final ChemElement MERCURY = new ChemElement(80);
    public static final ChemElement THALLIUM = new ChemElement(81);
    public static final ChemElement LEAD = new ChemElement(82);
    public static final ChemElement BISMUTH = new ChemElement(83);
    public static final ChemElement POLONIUM = new ChemElement(84);
    public static final ChemElement ASTATINE = new ChemElement(85);
    public static final ChemElement RADON = new ChemElement(86);
    public static final ChemElement FRANCIUM = new ChemElement(87);
    public static final ChemElement RADIUM = new ChemElement(88);
    public static final ChemElement ACTINIUM = new ChemElement(89);
    public static final ChemElement THORIUM = new ChemElement(90);
    public static final ChemElement PROTACTINIUM = new ChemElement(91);
    public static final ChemElement URANIUM = new ChemElement(92);
    public static final ChemElement NEPTUNIUM = new ChemElement(93);
    public static final ChemElement PLUTONIUM = new ChemElement(94);
    public static final ChemElement AMERICIUM = new ChemElement(95);
    public static final ChemElement CURIUM = new ChemElement(96);
    public static final ChemElement BERKELIUM = new ChemElement(97);
    public static final ChemElement CALIFORNIUM = new ChemElement(98);
    public static final ChemElement EINSTEINIUM = new ChemElement(99);
    public static final ChemElement FERMIUM = new ChemElement(100);
    public static final ChemElement MENDELEVIUM = new ChemElement(101);
    public static final ChemElement NOBELIUM = new ChemElement(102);
    public static final ChemElement LAWRENCIUM = new ChemElement(103);
    public static final ChemElement RUTHERFORDIUM = new ChemElement(104);
    public static final ChemElement DUBNIUM = new ChemElement(105);
    public static final ChemElement SEABORGIUM = new ChemElement(106);
    public static final ChemElement BOHRIUM = new ChemElement(107);
    public static final ChemElement HASSIUM = new ChemElement(108);
    public static final ChemElement MEITNERIUM = new ChemElement(109);
    public static final ChemElement DARMSTADTIUM = new ChemElement(110);
    public static final ChemElement ROENTGENIUM = new ChemElement(111);
    public static final ChemElement COPERNICIUM = new ChemElement(112);
    public static final ChemElement NIHONIUM = new ChemElement(113);
    public static final ChemElement FLEROVIUM = new ChemElement(114);
    public static final ChemElement MOSCOVIUM = new ChemElement(115);
    public static final ChemElement LIVERMORIUM = new ChemElement(116);
    public static final ChemElement TENNESSINE = new ChemElement(117);
    public static final ChemElement OGANESSON = new ChemElement(118);

    public static final ChemGas HYDROGEN_GAS = new ChemGas(new FabricItemSettings());
    public static final ChemGas NITROGEN_GAS = new ChemGas(new FabricItemSettings());
    public static final ChemGas OXYGEN_GAS = new ChemGas(new FabricItemSettings());
    public static final ChemGas FLUORINE_GAS = new ChemGas(new FabricItemSettings());
    public static final ChemGas CHLORINE_GAS = new ChemGas(new FabricItemSettings());
    public static final ChemGas HELIUM_GAS = new ChemGas(new FabricItemSettings().rarity(Rarity.RARE));
    public static final ChemGas NEON_GAS = new ChemGas(new FabricItemSettings().rarity(Rarity.RARE));
    public static final ChemGas ARGON_GAS = new ChemGas(new FabricItemSettings().rarity(Rarity.RARE));
    public static final ChemGas KRYPTON_GAS = new ChemGas(new FabricItemSettings().rarity(Rarity.RARE));
    public static final ChemGas XENON_GAS = new ChemGas(new FabricItemSettings().rarity(Rarity.RARE));

    public static final ChemLiquid BROMINE_LIQUID = new ChemLiquid(new FabricItemSettings());
    public static final ChemMetal MERCURY_METAL = new ChemMetal(new FabricItemSettings());

    @Override
    public void onInitialize() {
        LOGGER.info("Hello Fabric world!");
        registerAll();
    }

    private void registerAll() {
        registerItems();
        registerBlocks();
        registerBlockItems();
    }

    private void registerItems() {
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hydrogen_gas"), HYDROGEN_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nitrogen_gas"), NITROGEN_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "oxygen_gas"), OXYGEN_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "fluorine_gas"), FLUORINE_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "chlorine_gas"), CHLORINE_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "helium_gas"), HELIUM_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neon_gas"), NEON_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "argon_gas"), ARGON_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "krypton_gas"), KRYPTON_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "xenon_gas"), XENON_GAS);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bromine_liquid"), BROMINE_LIQUID);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "mercury_metal"), MERCURY_METAL);
    }

    private void registerBlocks() {
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "hydrogen"), HYDROGEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "helium"), HELIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lithium"), LITHIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "beryllium"), BERYLLIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "boron"), BORON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "carbon"), CARBON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nitrogen"), NITROGEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "oxygen"), OXYGEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "fluorine"), FLUORINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "neon"), NEON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "sodium"), SODIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "magnesium"), MAGNESIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "aluminium"), ALUMINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "silicon"), SILICON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "phosphorus"), PHOSPHORUS);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "sulfur"), SULFUR);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "chlorine"), CHLORINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "argon"), ARGON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "potassium"), POTASSIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "calcium"), CALCIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "scandium"), SCANDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "titanium"), TITANIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "vanadium"), VANADIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "chromium"), CHROMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "manganese"), MANGANESE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "iron"), IRON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cobalt"), COBALT);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nickel"), NICKEL);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "copper"), COPPER);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "zinc"), ZINC);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "gallium"), GALLIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "germanium"), GERMANIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "arsenic"), ARSENIC);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "selenium"), SELENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "bromine"), BROMINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "krypton"), KRYPTON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rubidium"), RUBIDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "strontium"), STRONTIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "yttrium"), YTTRIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "zirconium"), ZIRCONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "niobium"), NIOBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "molybdenum"), MOLYBDENUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "technetium"), TECHNETIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "ruthenium"), RUTHENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rhodium"), RHODIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "palladium"), PALLADIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "silver"), SILVER);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cadmium"), CADMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "indium"), INDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tin"), TIN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "antimony"), ANTIMONY);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tellurium"), TELLURIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "iodine"), IODINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "xenon"), XENON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cesium"), CESIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "barium"), BARIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lanthanum"), LANTHANUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "cerium"), CERIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "praseodymium"), PRASEODYMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "neodymium"), NEODYMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "promethium"), PROMETHIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "samarium"), SAMARIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "europium"), EUROPIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "gadolinium"), GADOLINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "terbium"), TERBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "dysprosium"), DYSPROSIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "holmium"), HOLMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "erbium"), ERBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "thulium"), THULIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "ytterbium"), YTTERBIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lutetium"), LUTETIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "hafnium"), HAFNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tantalum"), TANTALUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tungsten"), TUNGSTEN);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rhenium"), RHENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "osmium"), OSMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "iridium"), IRIDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "platinum"), PLATINUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "gold"), GOLD);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "mercury"), MERCURY);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "thallium"), THALLIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lead"), LEAD);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "bismuth"), BISMUTH);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "polonium"), POLONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "astatine"), ASTATINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "radon"), RADON);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "francium"), FRANCIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "radium"), RADIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "actinium"), ACTINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "thorium"), THORIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "protactinium"), PROTACTINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "uranium"), URANIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "neptunium"), NEPTUNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "plutonium"), PLUTONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "americium"), AMERICIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "curium"), CURIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "berkelium"), BERKELIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "californium"), CALIFORNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "einsteinium"), EINSTEINIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "fermium"), FERMIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "mendelevium"), MENDELEVIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nobelium"), NOBELIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "lawrencium"), LAWRENCIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "rutherfordium"), RUTHERFORDIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "dubnium"), DUBNIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "seaborgium"), SEABORGIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "bohrium"), BOHRIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "hassium"), HASSIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "meitnerium"), MEITNERIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "darmstadtium"), DARMSTADTIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "roentgenium"), ROENTGENIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "copernicium"), COPERNICIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "nihonium"), NIHONIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "flerovium"), FLEROVIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "moscovium"), MOSCOVIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "livermorium"), LIVERMORIUM);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "tennessine"), TENNESSINE);
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID, "oganesson"), OGANESSON);
    }

    private void registerBlockItems() {
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hydrogen"), new ChemElementBlockItem(HYDROGEN, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "helium"), new ChemElementBlockItem(HELIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lithium"), new ChemElementBlockItem(LITHIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "beryllium"), new ChemElementBlockItem(BERYLLIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "boron"), new ChemElementBlockItem(BORON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "carbon"), new ChemElementBlockItem(CARBON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nitrogen"), new ChemElementBlockItem(NITROGEN, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "oxygen"), new ChemElementBlockItem(OXYGEN, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "fluorine"), new ChemElementBlockItem(FLUORINE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neon"), new ChemElementBlockItem(NEON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "sodium"), new ChemElementBlockItem(SODIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "magnesium"), new ChemElementBlockItem(MAGNESIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "aluminium"), new ChemElementBlockItem(ALUMINIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "silicon"), new ChemElementBlockItem(SILICON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "phosphorus"), new ChemElementBlockItem(PHOSPHORUS, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "sulfur"), new ChemElementBlockItem(SULFUR, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "chlorine"), new ChemElementBlockItem(CHLORINE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "argon"), new ChemElementBlockItem(ARGON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "potassium"), new ChemElementBlockItem(POTASSIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "calcium"), new ChemElementBlockItem(CALCIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "scandium"), new ChemElementBlockItem(SCANDIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "titanium"), new ChemElementBlockItem(TITANIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "vanadium"), new ChemElementBlockItem(VANADIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "chromium"), new ChemElementBlockItem(CHROMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "manganese"), new ChemElementBlockItem(MANGANESE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "iron"), new ChemElementBlockItem(IRON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cobalt"), new ChemElementBlockItem(COBALT, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nickel"), new ChemElementBlockItem(NICKEL, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "copper"), new ChemElementBlockItem(COPPER, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "zinc"), new ChemElementBlockItem(ZINC, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "gallium"), new ChemElementBlockItem(GALLIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "germanium"), new ChemElementBlockItem(GERMANIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "arsenic"), new ChemElementBlockItem(ARSENIC, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "selenium"), new ChemElementBlockItem(SELENIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bromine"), new ChemElementBlockItem(BROMINE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "krypton"), new ChemElementBlockItem(KRYPTON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rubidium"), new ChemElementBlockItem(RUBIDIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "strontium"), new ChemElementBlockItem(STRONTIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "yttrium"), new ChemElementBlockItem(YTTRIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "zirconium"), new ChemElementBlockItem(ZIRCONIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "niobium"), new ChemElementBlockItem(NIOBIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "molybdenum"), new ChemElementBlockItem(MOLYBDENUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "technetium"), new ChemElementBlockItem(TECHNETIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "ruthenium"), new ChemElementBlockItem(RUTHENIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rhodium"), new ChemElementBlockItem(RHODIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "palladium"), new ChemElementBlockItem(PALLADIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "silver"), new ChemElementBlockItem(SILVER, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cadmium"), new ChemElementBlockItem(CADMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "indium"), new ChemElementBlockItem(INDIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tin"), new ChemElementBlockItem(TIN, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "antimony"), new ChemElementBlockItem(ANTIMONY, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tellurium"), new ChemElementBlockItem(TELLURIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "iodine"), new ChemElementBlockItem(IODINE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "xenon"), new ChemElementBlockItem(XENON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cesium"), new ChemElementBlockItem(CESIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "barium"), new ChemElementBlockItem(BARIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lanthanum"), new ChemElementBlockItem(LANTHANUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "cerium"), new ChemElementBlockItem(CERIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "praseodymium"), new ChemElementBlockItem(PRASEODYMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neodymium"), new ChemElementBlockItem(NEODYMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "promethium"), new ChemElementBlockItem(PROMETHIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "samarium"), new ChemElementBlockItem(SAMARIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "europium"), new ChemElementBlockItem(EUROPIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "gadolinium"), new ChemElementBlockItem(GADOLINIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "terbium"), new ChemElementBlockItem(TERBIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "dysprosium"), new ChemElementBlockItem(DYSPROSIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "holmium"), new ChemElementBlockItem(HOLMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "erbium"), new ChemElementBlockItem(ERBIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "thulium"), new ChemElementBlockItem(THULIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "ytterbium"), new ChemElementBlockItem(YTTERBIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lutetium"), new ChemElementBlockItem(LUTETIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hafnium"), new ChemElementBlockItem(HAFNIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tantalum"), new ChemElementBlockItem(TANTALUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tungsten"), new ChemElementBlockItem(TUNGSTEN, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rhenium"), new ChemElementBlockItem(RHENIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "osmium"), new ChemElementBlockItem(OSMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "iridium"), new ChemElementBlockItem(IRIDIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "platinum"), new ChemElementBlockItem(PLATINUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "gold"), new ChemElementBlockItem(GOLD, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "mercury"), new ChemElementBlockItem(MERCURY, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "thallium"), new ChemElementBlockItem(THALLIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lead"), new ChemElementBlockItem(LEAD, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bismuth"), new ChemElementBlockItem(BISMUTH, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "polonium"), new ChemElementBlockItem(POLONIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "astatine"), new ChemElementBlockItem(ASTATINE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "radon"), new ChemElementBlockItem(RADON, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "francium"), new ChemElementBlockItem(FRANCIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "radium"), new ChemElementBlockItem(RADIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "actinium"), new ChemElementBlockItem(ACTINIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "thorium"), new ChemElementBlockItem(THORIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "protactinium"), new ChemElementBlockItem(PROTACTINIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "uranium"), new ChemElementBlockItem(URANIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "neptunium"), new ChemElementBlockItem(NEPTUNIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "plutonium"), new ChemElementBlockItem(PLUTONIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "americium"), new ChemElementBlockItem(AMERICIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "curium"), new ChemElementBlockItem(CURIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "berkelium"), new ChemElementBlockItem(BERKELIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "californium"), new ChemElementBlockItem(CALIFORNIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "einsteinium"), new ChemElementBlockItem(EINSTEINIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "fermium"), new ChemElementBlockItem(FERMIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "mendelevium"), new ChemElementBlockItem(MENDELEVIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nobelium"), new ChemElementBlockItem(NOBELIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "lawrencium"), new ChemElementBlockItem(LAWRENCIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "rutherfordium"), new ChemElementBlockItem(RUTHERFORDIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "dubnium"), new ChemElementBlockItem(DUBNIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "seaborgium"), new ChemElementBlockItem(SEABORGIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "bohrium"), new ChemElementBlockItem(BOHRIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "hassium"), new ChemElementBlockItem(HASSIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "meitnerium"), new ChemElementBlockItem(MEITNERIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "darmstadtium"), new ChemElementBlockItem(DARMSTADTIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "roentgenium"), new ChemElementBlockItem(ROENTGENIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "copernicium"), new ChemElementBlockItem(COPERNICIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "nihonium"), new ChemElementBlockItem(NIHONIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "flerovium"), new ChemElementBlockItem(FLEROVIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "moscovium"), new ChemElementBlockItem(MOSCOVIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "livermorium"), new ChemElementBlockItem(LIVERMORIUM, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "tennessine"), new ChemElementBlockItem(TENNESSINE, new FabricItemSettings()));
        Registry.register(Registry.ITEM, new Identifier(MOD_ID, "oganesson"), new ChemElementBlockItem(OGANESSON, new FabricItemSettings()));
    }
}
